### ISSUE TITLE
Error while importing data through OpenWeatherMap

### ISSUE THREAD

**Issue by Waseem85** [scls19fr/pandas_degreedays#2]
Hi, 
I am getting an error while running the example that you described. After I write
ts_temp = TemperatureProvider('OpenWeatherMap', api_key='').get_from_coordinates(0.34189, 46.5798114, '20120601', '20141215')
I get errors saying that ValueError: No JSON object could be decoded. The last line of the error messages is ValueError: All objects passed were None. 

Any idea why this is happening? 
Thanks

**Comment by scls19fr** [comment]
Did you give an api_key parameter ?

**Comment by scls19fr** [comment]
I'm closing this issue because I think this is related to 
https://github.com/scls19fr/openweathermap_requests

Feel free to open issue there.

Insure you have latest version installed

$ pip install git+https://github.com/scls19fr/openweathermap_requests.git
